import Modal from '../Modal';

const SaleTermsModal = ({
  nftName,
  open,
  handleClose,
}: {
  nftName: string;
  open: boolean;
  handleClose: () => void;
}): JSX.Element => (
  <Modal open={open} handleClose={handleClose}>
    <div className="text-xs text-black">
      <h3 className="text-lg font-bold mb-5">Terms of Service</h3>
      <p className="mb-3">
        I understand and agree that the {nftName} non-fungible token (NFT) that I am purchasing:
      </p>
      <p className="mb-3">
        (a) is a unique work of art,
        <br />
        (b) is not expected to have any future value or generate any future proceeds or financial
        gains.
      </p>

      <p className="mb-3">
        I acknowledge that this purchase bestows no rights and that there are no guarantees that any
        of the potential plans proposed by the organizers or community supporting this project will
        be executed.
      </p>

      <p className="mb-3">
        Users certify through purchase that they understand that, as the smart contract runs on the
        Ethereum network and is bound by their system and terms, there is no ability to revoke,
        reverse, or restore any transactions.
      </p>

      <p className="mb-3">
        Users and collectors of these NFTs are solely responsible for the safety and the management
        of their own private assets, which include but are not limited to the NFT, their Ethereum
        Wallets, as well as validating all transactions and contracts generated by this website
        prior to and after purchases.
      </p>

      <p className="mb-3">
        Any connected services included this website are provided “as is” and “as available” without
        any guarantee or warranty of any kind. Use of this website constitutes your agreement that
        you are accepting sole responsibility for any and all transactions involving {nftName}{' '}
        digital collectibles.
      </p>

      <p className="mb-3">
        By agreeing to these Terms of Service, you represent that you are at least the required age
        in your state or province of residence.
      </p>

      <p className="">
        You may not use our products and/or services for any illegal or unauthorized purpose nor may
        you, in the use of the Service, violate any laws in your jurisdiction (including but not
        limited to copyright laws).
      </p>

      <button></button>
    </div>
  </Modal>
);

export default SaleTermsModal;
